add_rules("mode.debug", "mode.release")

option("levimc_repo")
    set_default("https://github.com/LiteLDev/xmake-repo.git")
    set_showmenu(true)
    set_description("Set the levimc-repo path or url")
option_end()

option("target_type")
    set_default("client")
    set_showmenu(true)
    set_values("server", "client")
option_end()

add_repositories("levimc-repo " .. (get_config("levimc_repo") or "https://github.com/LiteLDev/xmake-repo.git"))

add_requires("levilamina 26.51.0", {configs = {target_type = get_config("target_type") or "client"}})
add_requires("levibuildscript")
add_requires("imgui v1.91.9", {configs = {shared = false, win32 = true, dx11 = true, no_demo_windows = true}})
add_requires("minhook", {configs = {shared = false}})
add_requires("zlib")

if not has_config("vs_runtime") then
    set_runtimes("MD")
end

-- LeviLamina 26.51 is built with clang-cl (LLVM 22); the generated Minecraft
-- headers rely on the clang frontend, so the mod must use the same toolchain.
set_toolchains("clang-cl")

-- The JSON files are the only translation sources. xmake scans this directory
-- on every project load and writes a transient resource manifest under build/;
-- adding a new *.json file therefore embeds it on the next build without a
-- Python script or a checked-in generated file.
rule("lholo.i18n.resources")
    on_load(function(target)
        local language_files = os.files("src/i18n/lang/*.json")
        if #language_files == 0 then
            raise("no language JSON files found in src/i18n/lang")
        end

        local manifest_dir = path.join(os.projectdir(), "build", "generated", "i18n")
        local manifest = path.join(manifest_dir, "Languages.rc")
        local lines = {
            "// GENERATED by xmake.lua; do not edit.",
            "#pragma code_page(65001)",
            ""
        }
        local identifiers = {}
        for _, language_file in ipairs(language_files) do
            local code = path.basename(language_file):upper():gsub("[^%w]", "_")
            local identifier = "LHOLO_LANG_" .. code
            if identifiers[identifier] then
                raise("language resource ID collision: " .. identifier)
            end
            identifiers[identifier] = true

            local absolute_path = path.unix(path.absolute(language_file))
            table.insert(lines, identifier .. " RCDATA \"" .. absolute_path .. "\"")
        end
        table.insert(lines, "")

        local content = table.concat(lines, "\n")
        local escaped_manifest = path.unix(path.absolute(manifest)):gsub("'", "''")
        local powershell = "$manifest = '" .. escaped_manifest .. "'\n"
            .. "$content = @'\n" .. content .. "\n'@\n"
            .. "$directory = Split-Path -Parent $manifest\n"
            .. "New-Item -ItemType Directory -Force -Path $directory | Out-Null\n"
            .. "[System.IO.File]::WriteAllText($manifest, $content, [System.Text.UTF8Encoding]::new($false))\n"
        os.vrunv("powershell", {"-NoProfile", "-NonInteractive", "-Command", powershell})
        target:add("files", manifest)
    end)
rule_end()

target("LHolo")
    add_rules("lholo.i18n.resources")
    add_rules("@levibuildscript/linkrule")
    add_rules("@levibuildscript/modpacker", {modVersion = "26.51.0"})
    add_shflags("/DELAYLOAD:bedrock_runtime.dll", {force = true})
    add_cxflags(
        "/utf-8",
        "/W4",
        "/w44265",
        "/w44289",
        "/w44296",
        "/w45263",
        "/w44738",
        "/w45204"
    )
    add_cxflags(
        "/EHs",
        "-Wno-microsoft-cast",
        "-Wno-invalid-offsetof",
        "-Wno-c++2b-extensions",
        "-Wno-microsoft-include",
        "-Wno-overloaded-virtual",
        "-Wno-ignored-qualifiers",
        "-Wno-missing-field-initializers",
        "-Wno-potentially-evaluated-expression",
        "-Wno-pragma-system-header-outside-header",
        {tools = {"clang_cl"}}
    )
    add_defines("NOMINMAX", "UNICODE")
    add_syslinks("user32", "comdlg32", "d3d11", "d3d12", "dxgi", "delayimp")
    add_packages("levilamina", "imgui", "minhook", "zlib")

    set_kind("shared")
    set_languages("c++20")

    add_files("src/**.cpp")
    add_includedirs("src")

    after_build(function (target)
        local package_dir = path.join(os.projectdir(), "bin", target:name())
        os.mkdir(package_dir)
        os.cp(path.join(os.projectdir(), "LICENSE"), path.join(package_dir, "LICENSE"))
    end)

target("LHoloLogicTests")
    add_rules("lholo.i18n.resources")
    set_kind("binary")
    set_languages("c++20")
    set_default(false)
    add_includedirs("src")
    add_files("src/i18n/**.cpp")
    add_files("src/input/ViewMoveBasis.cpp")
    add_files("src/projection/core/ProjectionLayoutRules.cpp")
    add_files("src/projection/runtime/ProjectionProgress.cpp")
    add_files("src/place/PlacementState.cpp")
    add_files("src/settings/SettingsStore.cpp")
    add_files("src/structure/StructureSession.cpp")
    add_files("src/structure/StructureUiState.cpp")
    add_files("src/structure/java_to_bedrock/JavaTextComponent.cpp")
    add_files("src/ui/HotkeyFormat.cpp")
    add_files("tests/logic/**.cpp")
    add_cxflags("/utf-8")
    add_syslinks("user32")
    add_packages("levilamina")
