#!/usr/bin/env python3
"""Embed the JSON language files from src/i18n/lang/ into
src/i18n/EmbeddedLanguages.h as raw string constants.

The generated header is committed (same convention as
GeneratedChunkerMappings.inc): regular builds never run this script. Re-run
it whenever a JSON file changes, and commit both files together.

Usage: python tools/i18n/embed_languages.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LANG_DIR = ROOT / "src" / "i18n" / "lang"
OUT = ROOT / "src" / "i18n" / "EmbeddedLanguages.h"

# Languages listed here must match the Language enum in Translator.h.
LANGUAGES = [
    ("SimplifiedChinese", "zh_CN.json"),
    ("English", "en_US.json"),
]

HEADER = """// LHolo - Embedded language file contents
//
// GENERATED by tools/i18n/embed_languages.py from src/i18n/lang/*.json.
// Do not edit: change the JSON files and re-run the script.
// Committed on purpose so builds do not depend on Python.

#pragma once

#include <string_view>
"""

ENTRY = """
// Source: lang/{file_name}
inline constexpr std::string_view kEmbedded{enum_name}LanguageJson{{R"lholo({content})lholo"}};
"""


def main() -> int:
    parts = [HEADER]
    for enum_name, file_name in LANGUAGES:
        path = LANG_DIR / file_name
        content = path.read_text(encoding="utf-8-sig").rstrip("\n")
        # Validate: a broken JSON must fail the embedding step, not the game.
        json.loads(content)
        parts.append(
            ENTRY.format(enum_name=enum_name, file_name=file_name, content=content)
        )
    parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
